---
title: "Iteration"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Define Functions

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x) < 3){
    stop("x should have at least 3 numbers")
  }
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(output_df)
}

```


## Lists 

```{r}
l = 
  list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, FALSE),
  summary = summary(rnorm(1000, mean = 5, sd = 3))
)

l[[3]]

l[["summar"]]

l$summary
```


## List of normals 

```{r}
list_norms = 
  list(
    a = rnorm(1000, mean = 2, sd = 1),
    b = rnorm(1000, mean = 5, sd = 3),
    c = rnorm(1000, mean = 20, sd = 1.2),
    d = rnorm(1000, mean = -12, sd = 0.5)
  )

mean_and_sd(list_norms[[1]]) ## using number instead of the name "a" b/c we are thinking of it as for loop elements, 1st element, 2nd element. 
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])

```


## for loop

Let's use a for loop to iterate over my list of normals.

```{r}
output = vector("list", length = 4)

for (i in 1:4){
  output[[i]] = mean_and_sd(list_norms[[i]])
}

```


Let's use map instead....

```{r}
## doing similar things as for loop, but in one line of code
output = map(list_norms, mean_and_sd)
 
output = map(list_norms, median)

output = map(list_norms, summary)

output = map(list_norms, IQR)

```







